### PR TITLE
exclude non-video tracks from sdp handling

### PR DESCRIPTION
**Pull request by fabianeichfeldt**
Added check for rtpmap before accessing it

### CODE REVIEW

**Comment by steabert** [comment]
Thanks!

Please also add a tag in the commit message that this closes #121

**Comment by fabianeichfeldt** [comment]
Thanks for your comments, and sorry for my late reply.
I've adapted the code and tested with all my cams (Axis, Dahua, Foscam, Siqura). But I can't test the audio stream.
What do you mean with deriving the clockrate from a table?

**Comment by steabert** [comment]
The last commit isn't really what I meant to say with handling static payload types, please revert to the eb4419d commit (that was perfectly fine!).

What I meant with handling static payload types is that for example, your SDP from #121 contains:
```
m=audio 0 RTP/AVP 0
c=IN IP4 0.0.0.0
b=AS:64
a=control:track2
```
here, since the media description (`m=` line) according to [the spec](https://tools.ietf.org/html/rfc4566#section-5.14) has a third field `RTP/AVP`, the fourth field is the RTP payload type(s). If the payload type is static (< 96), they are described in [a table] (https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml) listing the encoding name and clockrate, but if the payload type is dynamic (> 96), there should be an `rtpmap` field in the SDP that contains the encoding name and clockrate. So far, we have assumed a dynamic payload type in our code.

However, that's not in the scope of this fix, which just makes sure we properly ignore static payload types (instead of crashing). So if you would like to do this you could make a separate issue/PR for it. For now, we could just ignore anything without `rtpmap` like you did in your commits.

**Comment by fabianeichfeldt** [comment]
Ah, OK. Thanks for the explanation, I was totally wrong and reverted my last commit.

How could this static payload be tested? Is there a good tool to generate such a rtsp source?

**Comment by steabert** [comment]
We don't really need to handle static payload unless someone comes along that wants to have support for a specific (old) encoding.

**Comment by steabert** [comment]
I've released version `5.0.0` and a `5-stable` branch to continue work on version 5.
Can you rebase this against the `5-stable` branch instead?

On master, we moved to Typescript, and I already incorporated your changes there.

**Comment by fabianeichfeldt** [comment]
I think this can be closed. 
I can't reproduce the original problem, on master.

**Pull request closed without merging**
