### PR TITLE
Publish dist/ folder

### PR DESCRIPTION
**Pull request by gaetancollaud**
This change resolves issue #67.

I just added a `.npmignore` file with the exact same definition as `.gitignore` except for the `dist/` folder.

Don't forget to `yarn build` before publishing. It can be added as `prepublish` task if you want ?

And I added the ignore for the intellij folder as well.

### CODE REVIEW

**Comment by gaetancollaud** [comment]
Just to be sure I tried to publish on https://www.npmjs.com/package/gaetancollaud-media-stream-library and it works. ;)

**Comment by gaetancollaud** [comment]
Can I let the intellij stuff in .npmignore ? Because I cannot make another PR since this file doesn't exist yet.

**Comment by steabert** [comment]
Oh, you can just remove it from both files, and then stack a new commit on top with a new branch. That can then be a pull request that starts of the previous one.

However, I don't want to make this too complicated for this, so if you just stack the two commits in this pull request it's fine too.

**Comment by gaetancollaud** [comment]
Fix done in #75

**Pull request closed without merging**
