### PR TITLE
fix: digest auth - md5.js library not working on a browser build

### LINKED ISSUE #396: Missing dependency towards md5.js
**Describe the bug**
When running this in Node.js using JavaScript and CommonJS modules, I get the following runtime error.

```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'md5.js'
Require stack:
- .../node_modules/media-stream-library/dist/cjs/components/auth/digest.js
```

I think the `md5.js` `devDependencies` should be moved to `dependencies`. This will solve the issue for Node.js, but I don't know whether it will cause another issue for other runtimes.

**Environment (please complete the following information):**
 - OS: iOS
 - Browser Node.js v12.16.2
 - Version 7.0.3

### PR DESCRIPTION
**Pull request by reijosirila**
Fixes #396 where md5.js not working on a browser build. Using plain ts-md5 library that fixes Digest Auth on a browser build

### CODE REVIEW

**Comment by lekoaf** [comment]
Thank you for your PR! We'll take a look at it as soon as we can.

**Comment by steabert** [comment]
What's the impact on the size of the bundle? I think this was originally removed because of this, but I can see the point in having it work for the browser (I only ever tested auth with a node client).

**Comment by reijosirila** [comment]
Well currently is md5.js on a browser bundle since: https://github.com/AxisCommunications/media-stream-library-js/pull/402
And md5.js is not working a browser. Size impact is about 2KiB

**Comment by steabert** [comment]
LGTM, can you rebase and resolve any conflicts? Thanks!

**Comment by steabert** [comment]
Continued at #604

**Pull request closed without merging**
